### ISSUE TITLE
how to get serving endpoint URL for ch2 example?

### ISSUE THREAD

**Issue by lambdaofgod** [intro-to-ml-with-kubeflow/intro-to-ml-with-kubeflow-examples#138]
When I try to use URL specified in book I get

>>> Sorry, /seldon/mnist-classifier/api/v0.1/predictions is not a valid page

**Comment by GodefroyClair** [comment]
same here

**Comment by zinzinhust96** [comment]
hello @lambdaofgod  and @GodefroyClair 

Did you figure it out?
